spring:
  application:
    name: SeleniumStarter-prod
  datasource:
    url: jdbc:sqlserver://128.3.1.200:1443;databaseName=BRIDGEFN_LC
    username: sa
    password: homed2022!!pq
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

server:
  port: 8082
logging:
  level:
    root: INFO
    org.springframework: INFO

