spring:
  application:
    name: SeleniumStarter-dev
  datasource:
    url: jdbc:sqlserver://128.3.1.199:1443;databaseName=BRIDGEFN_LC
    username: sa
    password: homed2022!!pq
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

server:
  port: 8082
logging:
  level:
    root: INFO
    org.springframework: INFO

